spring:
  application:
    name: tender-service

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/tender_service
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  # Kafka Configuration
  kafka:
    consumer:
      group-id: tender-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

# Tender Service Specific Configuration
app:
  tender:
    max-bid-duration-days: 30
    min-bid-amount: 1000
    evaluation-criteria:
      technical-weight: 0.6
      financial-weight: 0.4

  workflow:
    stages:
      - DRAFT
      - PUBLISHED
      - BIDDING
      - EVALUATION
      - AWARDED
      - CANCELLED

# Server Configuration
server:
  port: 8082
  servlet:
    context-path: /api/tenders
  tomcat:
    max-threads: 200
    max-connections: 300

# Custom Feature Toggles
features:
  tender-creation: true
  bid-submission: true
  auto-evaluation: false
  notification-service: true