# Common configuration for all services
spring:
  profiles:
    active: dev

  # Global Jackson configuration
  jackson:
    serialization:
      INDENT_OUTPUT: true
    default-property-inclusion: non_null

  # Resilience4j Circuit Breaker configuration
  cloud:
    loadbalancer:
      enabled: true

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus

  # Health check details
  health:
    circuitbreakers:
      enabled: true
    dependencies:
      enabled: true

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Resilience4j Circuit Breaker default configuration
resilience4j:
  circuitbreaker:
    instances:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3

# Kafka common configuration
kafka:
  bootstrap-servers: localhost:9092
  topics:
    user-events: user-events
    tender-events: tender-events

# Kafka Consumer Configuration
kafka-consumer-config:
  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  consumer-group-id: service-consumer-group
  auto-offset-reset: earliest
  batch-listener: true
  auto-startup: true
  concurrency-level: 3
  session-timeout-ms: 10000
  heartbeat-interval-ms: 3000
  max-poll-interval-ms: 300000
  max-poll-records: 500

# Kafka Producer Configuration
kafka-producer-config:
  key-serializer: org.apache.kafka.common.serialization.StringSerializer
  value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  acks: all
  batch-size: 16384
  linger-ms: 5
  request-timeout-ms: 30000
  retry-count: 5
  compression-type: 1
  compression-codec: gzip