spring:
  application:
    name: user-service

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  # Kafka Configuration
  kafka:
    consumer:
      group-id: user-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

# Application Specific Configuration
app:
  security:
    jwt:
      secret: your-256-bit-secret-for-user-service
      expiration: 86400000  # 24 hours

  validation:
    email-regex: ^[A-Za-z0-9+_.-]+@(.+)$
    password-complexity:
      min-length: 8
      require-uppercase: true
      require-lowercase: true
      require-digits: true
      require-special-chars: true

# Server Configuration
server:
  port: 8081
  servlet:
    context-path: /api/users
  tomcat:
    max-threads: 200
    max-connections: 300

# Custom Feature Toggles
features:
  user-registration: true
  email-verification: true
  two-factor-authentication: false